// examples/router/json/response.zig
//! JSON Response Utilities
//!
//! Comptime error messages and direct buffer writes for responses.
//! TigerStyle: Zero allocations, comptime where possible.

const std = @import("std");

// =============================================================================
// Comptime Error Messages (zero runtime cost)
// =============================================================================

/// Group of compile-time JSON error bodies used by the router response helpers.
/// Each field is a static `[]const u8` JSON payload generated by `comptimeJson` and can be returned without allocation.
/// Keep additions here aligned with handler and validation failure cases so response bodies stay consistent.
pub const errors = struct {
    /// Compile-time JSON body for the "missing request body" error.
    /// Use this when a request body is required but the caller supplied `null`.
    /// The string is generated at comptime and has static lifetime.
    pub const missing_body = comptimeJson("missing request body");
    /// Compile-time JSON body for the "empty request body" error.
    /// Use this when a request includes a body buffer but its length is zero.
    /// The value is a static JSON string and may be reused directly.
    pub const empty_body = comptimeJson("empty request body");
    /// Compile-time JSON body for the "request body too large" error.
    /// Use this when the received body exceeds the configured maximum size limit.
    /// The string is produced at comptime and requires no allocator.
    pub const body_too_large = comptimeJson("request body too large");
    /// Compile-time JSON body for the "JSON parse error" error.
    /// Use this for request bodies that fail JSON decoding before any higher-level validation can run.
    /// The value is static and owned by the program for its entire lifetime.
    pub const json_parse = comptimeJson("JSON parse error");
    /// Compile-time JSON body for the "no router configured" error.
    /// Use this when a request reaches logic that requires a router instance but none is available.
    /// The string is generated at comptime and can be returned directly.
    pub const no_router = comptimeJson("no router configured");
    /// Compile-time JSON body for the "route references invalid pool_idx" error.
    /// Use this when a route points at a pool index that is not valid in the current router state.
    /// The value is a static JSON string with no runtime allocation.
    pub const invalid_pool_idx = comptimeJson("route references invalid pool_idx");
    /// Compile-time JSON body for the "route must have path_prefix or path_exact" error.
    /// Use this value when a route definition omits both path selectors and the request must be rejected.
    /// The string is generated at comptime and does not allocate.
    pub const route_needs_path = comptimeJson("route must have path_prefix or path_exact");
    /// JSON error response used when a pool contains no upstreams.
    /// Returned by pool validation paths that require at least one upstream to be configured.
    pub const pool_no_upstreams = comptimeJson("pool has no upstreams");
    /// JSON error response used when a pool exceeds the allowed number of upstreams.
    /// Returned by pool validation paths that reject configurations with too many upstream entries.
    pub const pool_too_many_upstreams = comptimeJson("pool has too many upstreams");
    /// JSON error response used when a requested pool cannot be found.
    /// Returned by pool lookup and mutation paths that require an existing pool.
    pub const pool_not_found = comptimeJson("pool not found");
    /// JSON error response used when a requested route cannot be found.
    /// Returned by route lookup and mutation paths that require an existing route.
    pub const route_not_found = comptimeJson("route not found");
    /// JSON error response used when a route name already exists.
    /// Returned by route-creation paths to report a name collision without additional payload data.
    pub const route_exists = comptimeJson("route with this name already exists");
    /// Compile-time JSON string for the case where a pool name already exists.
    /// Use this in router response payloads when a duplicate pool name is rejected.
    pub const pool_exists = comptimeJson("pool with this name already exists");
    /// Compile-time JSON string for the case where a pool is still referenced by routes.
    /// Use this in router response payloads when removal is blocked by existing route references.
    pub const pool_referenced = comptimeJson("pool is referenced by routes");
    /// Compile-time JSON string for the case where too many routes were configured.
    /// Use this in router response payloads when route creation exceeds the supported limit.
    pub const too_many_routes = comptimeJson("too many routes");
    /// Compile-time JSON string for the case where too many pools were configured.
    /// Use this in router response payloads when pool creation exceeds the supported limit.
    pub const too_many_pools = comptimeJson("too many pools");
    /// Compile-time JSON string for the allowed-hosts limit.
    /// Use this in router response payloads when the configured allowed_hosts set is too large.
    pub const too_many_allowed_hosts = comptimeJson("too many allowed_hosts");
    /// Compile-time JSON string for the maximum-routes limit.
    /// Use this in router response payloads when the router cannot accept any more routes.
    pub const max_routes = comptimeJson("maximum routes reached");
    /// Compile-time JSON string for the maximum-pools limit.
    /// Use this in router response payloads when the router cannot accept any more pools.
    pub const max_pools = comptimeJson("maximum pools reached");
    /// Compile-time JSON string for the maximum-upstreams-per-pool limit.
    /// Use this in router response payloads when a pool cannot accept any more upstream entries.
    pub const max_upstreams = comptimeJson("maximum upstreams per pool reached");
    /// Compile-time JSON string for an upstream idx that exceeds the supported maximum.
    /// Use this in router response payloads when an upstream index is out of range.
    pub const upstream_idx_max = comptimeJson("upstream idx exceeds maximum");
    /// Compile-time JSON string for the case where an upstream idx already exists in a pool.
    /// Use this in router response payloads when a duplicate upstream index is rejected.
    pub const upstream_exists = comptimeJson("upstream with this idx already exists in pool");
    /// Compile-time JSON string for the rule that the last pool cannot be removed.
    /// Use this in router response payloads when deletion would leave the router with no pools.
    pub const last_pool = comptimeJson("cannot remove last pool");
    /// Compile-time JSON string for the rule that the last upstream in a pool cannot be removed.
    /// Use this in router response payloads when removal would leave the pool empty.
    pub const last_upstream = comptimeJson("cannot remove last upstream from pool");
    /// Compile-time JSON string for a lookup failure where an upstream is not present in a pool.
    /// Use this in router response payloads when a requested upstream cannot be found.
    pub const upstream_not_found = comptimeJson("upstream not found in pool");
    /// Compile-time JSON string for a failed router swap operation.
    /// Use this in router response payloads when a swap cannot be completed successfully.
    pub const swap_failed = comptimeJson("router swap failed");
    /// Compile-time JSON string for a response buffer overflow condition.
    /// Use this in router response payloads when the encoded response does not fit the buffer.
    pub const buffer_overflow = comptimeJson("response buffer overflow");
    /// Compile-time JSON string for the case where a pool must contain at least one upstream.
    /// Use this in router response payloads when validation rejects an empty pool.
    pub const at_least_one_pool = comptimeJson("at least one pool is required");
};

fn comptimeJson(comptime msg: []const u8) []const u8 {
    return std.fmt.comptimePrint("{{\"error\":\"{s}\"}}", .{msg});
}

// =============================================================================
// Dynamic Responses (direct buffer write, no allocator)
// =============================================================================

/// Format success response with generation.
pub fn success(buf: []u8, generation: u64) []const u8 {
    return std.fmt.bufPrint(buf, "{{\"status\":\"ok\",\"generation\":{d}}}", .{generation}) catch
        "{\"status\":\"ok\"}";
}

/// Format success response with generation and pool_idx.
pub fn poolAdded(buf: []u8, generation: u64, pool_idx: usize) []const u8 {
    return std.fmt.bufPrint(buf, "{{\"status\":\"ok\",\"generation\":{d},\"pool_idx\":{d}}}", .{ generation, pool_idx }) catch
        "{\"status\":\"ok\"}";
}

// =============================================================================
// Body Validation (shared by admin handlers)
// =============================================================================

/// Result of body validation - either the valid body or an error response.
pub const BodyValidation = union(enum) {
    valid: []const u8,
    err: ErrorResult,
};

/// Error result for returning from handlers.
pub const ErrorResult = struct {
    status: u16,
    body: []const u8,
};

/// Validate request body for admin endpoints.
/// Returns the body if valid, or an error result to return immediately.
/// TigerStyle: Consolidates repeated validation logic.
pub fn validateBody(body: ?[]const u8, max_size: u32) BodyValidation {
    const request_body = body orelse {
        return .{ .err = .{ .status = 400, .body = errors.missing_body } };
    };

    if (request_body.len == 0) {
        return .{ .err = .{ .status = 400, .body = errors.empty_body } };
    }

    if (request_body.len > max_size) {
        return .{ .err = .{ .status = 413, .body = errors.body_too_large } };
    }

    return .{ .valid = request_body };
}
